# Hardware configuration file for collison avodance robot

NUMBER_PIXELS = 2
NEOPIXEL_PIN = 18

SPEAKER_PIN = 22

MOTOR_RIGHT_FORWARD = 11
MOTOR_RIGHT_BACKWARD = 10
MOTOR_LEFT_FORWARD = 8
MOTOR_LEFT_REVERSE = 9

TOF_SDA_PIN = 26
TOF_SCL_PIN = 27
TOF_I2C_BUS = 1