MAX_POWER_LEVEL = 65025

NUMBER_PIXELS = 64
NEOPIXEL_PIN = 6

SPEAKER_PIN = 22

TOF_SDA_PIN = 16
TOF_SCL_PIN = 17
TOF_I2C_BUS = 0

# lower right pins with USB on top
MOTOR_RIGHT_FORWARD_PIN = 9
MOTOR_RIGHT_REVERSE_PIN = 8
MOTOR_LEFT_FORWARD_PIN = 10
MOTOR_LEFT_REVERSE_PIN = 11